export const missionSnapshot = {
  mission: { id: "ORBIT-42", status: "OPERATIONAL", scenario: "Thermal Anomaly" },
  metrics: { activeAnomalies: 1, systemsMonitored: 6, evidenceSources: 128 },
  anomaly: {
    system: "THERMAL SYSTEM",
    severity: "HIGH SEVERITY",
    temperatureC: 89.2,
    normalRangeC: [60, 80] as const,
    detectedAt: "14:32:04",
    description:
      "Thermal system temperature exceeded the expected operating range following a reduction in cooling fan RPM.",
  },
  telemetry: [
    { time: "14:25", temperature: 71.8, fanRpm: 4200, voltage: 12.1 },
    { time: "14:26", temperature: 71.9, fanRpm: 4190, voltage: 12.1 },
    { time: "14:27", temperature: 71.9, fanRpm: 4180, voltage: 12.08 },
    { time: "14:28", temperature: 72.0, fanRpm: 4200, voltage: 12.08 },
    { time: "14:29", temperature: 72.0, fanRpm: 4200, voltage: 12.06 },
    { time: "14:30", temperature: 72.0, fanRpm: 4200, voltage: 12.05 },
    { time: "14:31", temperature: 73.1, fanRpm: 1800, voltage: 12.02 },
    { time: "14:32", temperature: 78.4, fanRpm: 1820, voltage: 11.96 },
    { time: "14:33", temperature: 85.5, fanRpm: 1810, voltage: 11.89 },
    { time: "14:34", temperature: 89.2, fanRpm: 1800, voltage: 11.84 },
    { time: "14:35", temperature: 89.2, fanRpm: 1800, voltage: 11.8 },
  ],
  systems: [
    { name: "THERMAL", status: "WARNING", state: "warning" },
    { name: "POWER", status: "NOMINAL", state: "healthy" },
    { name: "COMMUNICATIONS", status: "NOMINAL", state: "healthy" },
    { name: "PROPULSION", status: "NOMINAL", state: "healthy" },
    { name: "NAVIGATION", status: "NOMINAL", state: "healthy" },
    { name: "LIFE SUPPORT", status: "NOMINAL", state: "healthy" },
  ],
  events: [
    {
      time: "14:30:00",
      level: "INFO",
      code: "SYSTEM_NOMINAL",
      title: "System nominal",
      detail: "Thermal temperature 72°C",
      state: "healthy",
    },
    {
      time: "14:31:12",
      level: "WARNING",
      code: "FAN_SPEED_LOW",
      title: "Cooling fan speed below threshold",
      detail: "Fan RPM dropped from 4200 → 1800",
      state: "warning",
    },
    {
      time: "14:32:04",
      level: "HIGH",
      code: "TEMP_THRESHOLD_EXCEEDED",
      title: "Temperature anomaly detected",
      detail: "Thermal reading exceeded the 80°C operating limit",
      state: "critical",
    },
    {
      time: "14:33:18",
      level: "HIGH",
      code: "THERMAL_WARNING",
      title: "Thermal system warning",
      detail: "Temperature reached 89.2°C",
      state: "critical",
    },
  ],
} as const;
